# Generated by Django 4.0.4 on 2022-08-24 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=100)),
                ('userpw', models.CharField(db_column='userPW', max_length=128)),
                ('gender', models.IntegerField()),
                ('nationality', models.CharField(max_length=45)),
                ('createdat', models.DateTimeField(
                    blank=True, db_column='createdAt', null=True)),
                ('updatedat', models.DateTimeField(
                    blank=True, db_column='updatedAt', null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usermedicalinfo',
            fields=[
                ('userid', models.OneToOneField(db_column='userID', on_delete=django.db.models.deletion.DO_NOTHING,
                 primary_key=True, serialize=False, to='users.user')),
                ('rash', models.IntegerField()),
                ('fever', models.IntegerField()),
                ('headache', models.IntegerField()),
                ('backpain', models.IntegerField()),
                ('musclepain', models.IntegerField()),
                ('lymphedema', models.IntegerField()),
                ('lethargy', models.IntegerField()),
                ('diagnosed', models.IntegerField()),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('image', models.ImageField(
                    blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'userMedicalInfo',
                'managed': False,
            },
        ),
    ]
