# Generated by Django 4.0.3 on 2022-08-17 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=100)),
                ('userpw', models.CharField(db_column='userPW', max_length=100)),
                ('gender', models.IntegerField()),
                ('nationality', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usermedicalinfo',
            fields=[
                ('userid', models.OneToOneField(db_column='userID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='users.user')),
                ('rash', models.IntegerField()),
                ('fever', models.IntegerField()),
                ('headache', models.IntegerField()),
                ('backpain', models.IntegerField()),
                ('musclepain', models.IntegerField()),
                ('lymphedema', models.IntegerField()),
                ('lethargy', models.IntegerField()),
                ('diagnosed', models.IntegerField()),
            ],
            options={
                'db_table': 'userMedicalInfo',
                'managed': False,
            },
        ),
    ]
